language: cpp

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lcov

before_script:
- mkdir build
- cd build
- cmake ..

script: make

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -t 8d9d1950-59a4-4bbd-95ad-a248e8815647 || echo "Codecov did not collect 


